# Generated by Django 4.1 on 2022-12-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_file_files_parsingstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='files',
            new_name='user',
        ),
    ]
