# Generated by Django 4.1 on 2022-12-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_files_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingstatus',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='inventory.file'),
        ),
    ]
